project:
  type: website
  output-dir: docs
  
website:
  title: "Daniel Ramos"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About


html:
  theme: [cosmo, styles.scss]
  toc: true

editor: visual

